{
 "title": "Goldenroute traffic",
 "tags": [
  "goldenroute",
  "iptables",
  "proxy",
  "traffic"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Direct",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(goldenroute_traffic_bytes_total{path=\"direct\"}[1m])) * 8",
     "legendFormat": "now"
    },
    {
     "expr": "avg_over_time((sum(irate(goldenroute_traffic_bytes_total{path=\"direct\"}[1m])) * 8)[$__range:5s])",
     "legendFormat": "avg"
    },
    {
     "expr": "max_over_time((sum(irate(goldenroute_traffic_bytes_total{path=\"direct\"}[1m])) * 8)[$__range:5s])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "WSProxy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(goldenroute_traffic_bytes_total{path=\"wsproxy\"}[1m])) * 8",
     "legendFormat": "now"
    },
    {
     "expr": "avg_over_time((sum(irate(goldenroute_traffic_bytes_total{path=\"wsproxy\"}[1m])) * 8)[$__range:5s])",
     "legendFormat": "avg"
    },
    {
     "expr": "max_over_time((sum(irate(goldenroute_traffic_bytes_total{path=\"wsproxy\"}[1m])) * 8)[$__range:5s])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Tor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(goldenroute_traffic_bytes_total{path=\"tor\"}[1m])) * 8",
     "legendFormat": "now"
    },
    {
     "expr": "avg_over_time((sum(irate(goldenroute_traffic_bytes_total{path=\"tor\"}[1m])) * 8)[$__range:5s])",
     "legendFormat": "avg"
    },
    {
     "expr": "max_over_time((sum(irate(goldenroute_traffic_bytes_total{path=\"tor\"}[1m])) * 8)[$__range:5s])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "↓ Speed in",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(goldenroute_traffic_bytes_total{path=\"direct\",direction=\"in\"}[1m]) * 8",
     "legendFormat": "Direct"
    },
    {
     "expr": "irate(goldenroute_traffic_bytes_total{path=\"wsproxy\",direction=\"in\"}[1m]) * 8",
     "legendFormat": "WSProxy"
    },
    {
     "expr": "irate(goldenroute_traffic_bytes_total{path=\"tor\",direction=\"in\"}[1m]) * 8",
     "legendFormat": "Tor"
    }
   ]
  },
  {
   "title": "↑ Speed out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(goldenroute_traffic_bytes_total{path=\"direct\",direction=\"out\"}[1m]) * 8",
     "legendFormat": "Direct"
    },
    {
     "expr": "irate(goldenroute_traffic_bytes_total{path=\"wsproxy\",direction=\"out\"}[1m]) * 8",
     "legendFormat": "WSProxy"
    },
    {
     "expr": "irate(goldenroute_traffic_bytes_total{path=\"tor\",direction=\"out\"}[1m]) * 8",
     "legendFormat": "Tor"
    }
   ]
  },
  {
   "title": "↓ Volume in",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "goldenroute_traffic_bytes_total{path=\"direct\",direction=\"in\"} - goldenroute_traffic_bytes_total{path=\"direct\",direction=\"in\"} @ start()",
     "legendFormat": "Direct"
    },
    {
     "expr": "goldenroute_traffic_bytes_total{path=\"wsproxy\",direction=\"in\"} - goldenroute_traffic_bytes_total{path=\"wsproxy\",direction=\"in\"} @ start()",
     "legendFormat": "WSProxy"
    },
    {
     "expr": "goldenroute_traffic_bytes_total{path=\"tor\",direction=\"in\"} - goldenroute_traffic_bytes_total{path=\"tor\",direction=\"in\"} @ start()",
     "legendFormat": "Tor"
    }
   ]
  },
  {
   "title": "↑ Volume out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "goldenroute_traffic_bytes_total{path=\"direct\",direction=\"out\"} - goldenroute_traffic_bytes_total{path=\"direct\",direction=\"out\"} @ start()",
     "legendFormat": "Direct"
    },
    {
     "expr": "goldenroute_traffic_bytes_total{path=\"wsproxy\",direction=\"out\"} - goldenroute_traffic_bytes_total{path=\"wsproxy\",direction=\"out\"} @ start()",
     "legendFormat": "WSProxy"
    },
    {
     "expr": "goldenroute_traffic_bytes_total{path=\"tor\",direction=\"out\"} - goldenroute_traffic_bytes_total{path=\"tor\",direction=\"out\"} @ start()",
     "legendFormat": "Tor"
    }
   ]
  }
 ]
}